/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dfe2ee",
        "surface-container": "#1c2028",
        "primary-fixed": "#acedff",
        "tertiary-container": "#e79400",
        "background": "#0f131c",
        "surface-tint": "#4cd7f6",
        "on-tertiary": "#472a00",
        "secondary-fixed": "#ffdad7",
        "on-secondary": "#68000a",
        "surface-bright": "#353942",
        "surface-variant": "#31353e",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2c3039",
        "on-error": "#690005",
        "tertiary": "#ffb95f",
        "on-surface-variant": "#bcc9cd",
        "primary-container": "#06b6d4",
        "surface-dim": "#0f131c",
        "secondary": "#ffb3ad",
        "primary": "#4cd7f6",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed": "#001f26",
        "outline": "#869397",
        "on-primary-container": "#00424f",
        "secondary-fixed-dim": "#ffb3ad",
        "secondary-container": "#a40217",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-low": "#181c24",
        "surface": "#0f131c",
        "primary-fixed-dim": "#4cd7f6",
        "error-container": "#93000a",
        "surface-container-high": "#262a33",
        "on-tertiary-fixed-variant": "#653e00",
        "on-background": "#dfe2ee",
        "on-surface": "#dfe2ee",
        "surface-container-lowest": "#0a0e16",
        "on-secondary-container": "#ffaea8",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-primary": "#00687a",
        "on-secondary-fixed-variant": "#930013",
        "on-tertiary-container": "#563400",
        "on-primary-fixed-variant": "#004e5c",
        "surface-container-highest": "#31353e",
        "on-secondary-fixed": "#410004",
        "outline-variant": "#3d494c",
        "on-primary": "#003640"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "grid-margin-mobile": "0.75rem",
        "gutter-lg": "1rem",
        "panel-padding-standard": "1rem",
        "gutter-md": "0.75rem",
        "panel-padding-spacious": "1.5rem",
        "grid-margin-desktop": "1.5rem",
        "panel-padding-tight": "0.5rem",
        "module-gap": "1.25rem",
        "gutter-xs": "0.25rem",
        "gutter-sm": "0.5rem"
      },
      fontFamily: {
        "body-md": [ "Inter", "sans-serif" ],
        "headline-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-xl": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-mono-lg": [ "JetBrains Mono", "monospace" ],
        "headline-xl-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-lg-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-sm": [ "Inter", "sans-serif" ],
        "body-lg": [ "Inter", "sans-serif" ],
        "headline-md": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-mono-md": [ "JetBrains Mono", "monospace" ],
        "headline-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-mono-sm": [ "JetBrains Mono", "monospace" ]
      },
      fontSize: {
        "body-md": [ "14px", { "lineHeight": "20px", "fontWeight": "400" } ],
        "headline-lg": [ "32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" } ],
        "headline-xl": [ "40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" } ],
        "label-mono-lg": [ "14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" } ],
        "headline-xl-mobile": [ "28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "800" } ],
        "headline-lg-mobile": [ "24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" } ],
        "body-sm": [ "12px", { "lineHeight": "16px", "fontWeight": "400" } ],
        "body-lg": [ "16px", { "lineHeight": "24px", "fontWeight": "400" } ],
        "headline-md": [ "22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "700" } ],
        "label-mono-md": [ "12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "500" } ],
        "headline-sm": [ "18px", { "lineHeight": "24px", "fontWeight": "600" } ],
        "label-mono-sm": [ "10px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "500" } ]
      }
    }
  },
  plugins: [],
}
